language: cpp
sudo: false

matrix:
  include:
    # GCC5 on Linux Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          # https://github.com/glfw/glfw/blob/master/.travis.yml
          packages:
            - cmake
            - g++-5
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env: COMPILER='g++-5'
    # Clang on OSX
    - os: osx
      osx_image: xcode10
      compiler: clang
      env: COMPILER='clang++'

before_install:
  # Install cmake
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install --upgrade cmake;
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake;
    fi
  # Get logical CPU number
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CPU_NUM=`grep -c ^processor /proc/cpuinfo`;
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      export CPU_NUM=`sysctl -n hw.logicalcpu_max`;
    fi

install:
  # On Trusty, please install glfw3 from source
  #   E: Unable to locate package libglfw3-dev
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip;
      unzip glfw-3.2.1.zip && cd glfw-3.2.1;
      cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON;
      make -j $CPU_NUM;
      sudo make install && cd ..;
    fi

before_script:

script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - make init
  - make install BUILD_OPTIONS="-j $CPU_NUM"
